### ISSUE TITLE
Recipe Improvements

### ISSUE THREAD

**Issue by SilentChaos512** [M4thG33k/Gemulation_1.9#1]
Two small suggestions for recipes in the mod:
1. Use ore dictionary keys in recipes, so that gems from other mods can be used. EnumGem contains getters for the ore dictionary keys, getItemOreName() and getItemSuperOreName().
2. Remove excess whitespace from recipes so that furnaces can be crafted in any column. Basically just change ..." m ", " f ", " m "... to ..."m", "f", "m". Just a minor inconvenience, but it's best to remove any rows/columns of all whitespace from recipes.

**Comment by M4thG33k** [comment]
Yeah...stupid me for not doing that in the first place. I'll try to get those fixed (the latter one is actually a part of LIT, but no big deal). I'll include both those fixes in the next update (whenever I actually am able to do that...)

**Comment by M4thG33k** [comment]
Have you registered your gems with the ore dictionary somewhere? For some reason, the recipes don't work if I use the getItemOreName() method. (They work for other ore dictionary materials [redstone], but not for the gems..)

**Comment by M4thG33k** [comment]
Upon inspection, it seems like you've registered the blocks/ores with the Ore Dictionary, but not the gems themselves...was this intentional?

**Comment by SilentChaos512** [comment]
Definitely not. Looks like I missed registering the items. I'll get that fixed right away.
