### ISSUE TITLE
[1.9] Breaking a chest drops 2 chest

### ISSUE THREAD

**Issue by kwpugh** [M4thG33k/Gemulation_1.9#3]
Forge 1887
Mod: gemulation-1.9-2.0.5.jar

**Comment by M4thG33k** [comment]
I know exactly what the issue is; I'll try to get a patch out later today/night when I get home. Thanks for letting me know!

**Comment by M4thG33k** [comment]
I'm assuming that it drops one chest that is empty and one that retains any inventory it had?

**Comment by kwpugh** [comment]
Yes.   It tried putting stuff in the chest and breaking it, one is empty, the other has the stuff.  No dipping of contents.

**Comment by M4thG33k** [comment]
Alright. So yeah, I know exactly what needs to be fixed. (The empty chest shouldn't be dropped at all, unless the chest itself is empty.) Retaining the contents of its inventory is the new feature. I'll fix this tonight.

**Comment by kwpugh** [comment]
Cool, thank you.   Nice mod by the way.

**Comment by M4thG33k** [comment]
No problem and thanks! If you have any suggestions for future content, let me know!
