### ISSUE TITLE
Shiny bag 

### ISSUE THREAD

**Issue by APolarBaer** [M4thG33k/Gemulation_1.9#4]
putting a graded gem into the bag and then dropping differently graded or ungraded gems allowing the bag to pick them up changes to the stored gems grade.
![screenshot 2016-06-09 14 14 23](https://cloud.githubusercontent.com/assets/19779692/15941040/90f59b9e-2e4c-11e6-965f-3ea8b19490e4.png)
![screenshot 2016-06-09 14 14 26](https://cloud.githubusercontent.com/assets/19779692/15941041/90fe659e-2e4c-11e6-85a1-ec995ea4ade7.png)
![screenshot 2016-06-09 14 14 34](https://cloud.githubusercontent.com/assets/19779692/15941043/90ff3ba4-2e4c-11e6-87db-a075c915559b.png)
![screenshot 2016-06-09 14 14 41](https://cloud.githubusercontent.com/assets/19779692/15941042/90feed7a-2e4c-11e6-93b0-f358aa695e50.png)

**Comment by M4thG33k** [comment]
Thanks for bringing this to my attention! A fix should be up shortly!

**Comment by APolarBaer** [comment]
no worries, glad to test stuff out ouo
